#!/bin/bash
#SBATCH --job-name=genome_metrics
#SBATCH --output=genome.metrics.log
#SBATCH --cpus-per-task=40
#SBATCH --partition=macmanes
#SBATCH --exclude=node117,node118
# echo commands to stdout
set -x

# set environments
module purge
module load linuxbrew/colsa

# variables
DIR=$(pwd)
ASSEMBLY=$1
BUSCO_OUT=$2

# setup
mkdir assembly_stats

echo RUNNING GENOME ASSEMBLY METRICS

##### Assemblathon stats analysis
echo Running assemblathon script
/mnt/lustre/macmaneslab/ams1236/software/assemblathon/assemblathon_stats.pl $ASSEMBLY | tee assembly_stats/${BUSCO_OUT}.stats

# print results
echo LENGTH AND CONTIGUITY RESULTS
cat assembly_stats/${BUSCO_OUT}.stats


###### BUSCO analysis
## Tetrapoda lineage
cp /mnt/lustre/macmaneslab/ams1236/Oyster_River_Protocol/busco_dbs/tetrapoda.config.ini .
mv tetrapoda.config.ini config.ini

export AUGUSTUS_CONFIG_PATH="/mnt/lustre/macmaneslab/ams1236/software/busco_info/config/"

busco -i ${ASSEMBLY} -m geno --cpu 40 -o ${BUSCO_OUT}
