#!/bin/bash

#SBATCH --partition=macmanes
#SBATCH -J bwa
#SBATCH --output bwa.log
#SBATCH --cpus-per-task=40
#SBATCH --exclude node117

DIR=$(pwd)
ASSEMBLY="merged_quickmerged_pacbio_alldata.fasta"

species="Ranitomeya_imitator"
prefix="Rimi"


READ1="Rimi_S1_L001_R1_001.fastq.gz"
READ2="Rimi_S1_L001_R2_001.fastq.gz"


module purge
module load linuxbrew/colsa

mkdir pilon_polish_rd1
cd pilon_polish_rd1

bwa index ${DIR}/${ASSEMBLY}

rm -f "$prefix".sorted.bam
rm -f "$prefix".sorted.bam.bai

bwa mem -t 40 ${DIR}/${ASSEMBLY} ${DIR}/raw_10xdata/${READ1} ${DIR}/raw_10xdata/${READ2} \
| samtools view -@20 -Sb - \
| samtools sort -T "$prefix" -O bam -@20 -l9 -m2G -o "$prefix".sorted.bam -
samtools index "$prefix".sorted.bam
