#!/usr/bin/sh
#SBATCH --mem=700GB
#SBATCH --job-name="wtdbg_alldata_pacbio"
#SBATCH --output="wtdbg_alldata_pacbio.log"
#SBATCH --partition=macmanes
#SBATCH --open-mode=append
#SBATCH --cpus-per-task=40
#SBATCH --exclude=node117
set -x

DIR=$(pwd)

module purge

mkdir wtdbg_alldata_pacbio
cd wtdbg_alldata_pacbio

wtdbg2 -x sq -g 6.7g -t 40 -i ${DIR}/masurca_assembly/combinedreads.fa -fo imitator.alldata.pacbiospec.wtdbg ### this is for nanopore
wtpoa-cns -t 40 -i imitator.alldata.pacbiospec.wtdbg.ctg.lay.gz -fo imitator.alldata.pacbiospec.wtdbg.ctg.fa
