#!/bin/bash
#SBATCH --partition=macmanes
#SBATCH --ntasks=40
#### #SBATCH --mem 700Gb
#SBATCH --open-mode=append
#SBATCH --exclude=node117
#SBATCH -J arcs
#SBATCH --output arcs.log
#### #SBATCH --dependency=afterany:278428_79


source /mnt/lustre/macmaneslab/ams1236/.bash_profile


conda activate base
module load linuxbrew/colsa

mkdir arcs_run

# copy data over from pilon run
cp /mnt/lustre/macmaneslab/ams1236/imitator_genome/imitator_merged_polished.fasta /mnt/lustre/macmaneslab/ams1236/imitator_genome/arcs_run/imitator_merged_polished.fa

/mnt/lustre/macmaneslab/ams1236/scripts/arcs.mk arcs draft=/mnt/lustre/macmaneslab/ams1236/imitator_genome/arcs_run/imitator_merged_polished reads=/mnt/lustre/macmaneslab/ams1236/imitator_genome/imitator10x/outs/barcoded
