#!/usr/bin/sh
#SBATCH --mem=700GB
#SBATCH --job-name="wtdbg_alldata_nano"
#SBATCH --output="wtdbg_alldata_nano.log"
#SBATCH --partition=macmanes
#SBATCH --open-mode=append
#SBATCH --cpus-per-task=40
#SBATCH --exclude=node117,node118
set -x


DIR=$(pwd)

module purge

mkdir wtdbg_alldata_nanopore
cd wtdbg_alldata_nanopore

wtdbg2 -x ont -g 6.7g -t 40 -i ${DIR}/masurca_assembly/combinedreads.fa -fo imitator.alldata.nanoporespec.wtdbg ### this is for nanopore
wtpoa-cns -t 40 -i imitator.alldata.nanoporespec.wtdbg.ctg.lay.gz -fo imitator.alldata.nanoporespec.wtdbg.ctg.fa
