#!/bin/bash
#SBATCH --job-name=busco4
#SBATCH --output=busco4.log
#SBATCH --cpus-per-task=40
#SBATCH --partition=macmanes
#SBATCH --exclude=node117,node118
# echo commands to stdout
set -x

module purge
conda activate BUSCO4

DIR=$(pwd)
ASSEMBLY=$1
BUSCO_OUT=$2



###### BUSCO analysis
rm config.ini

export AUGUSTUS_CONFIG_PATH="/mnt/lustre/macmaneslab/ams1236/software/busco_info/config/"

busco -i ${ASSEMBLY} -m geno --cpu 40 -o ${BUSCO_OUT} -l /mnt/lustre/macmaneslab/ams1236/imitator_genome/busco_downloads/lineages/tetrapoda_odb10
