#!/bin/bash
#SBATCH --partition=macmanes,shared
#SBATCH -J purge_haplotigs
#SBATCH --output purge_haplotigs.log
#SBATCH --cpus-per-task=40
#SBATCH --exclude=node117,node118

DIR=$(pwd)
ASSEMBLY="$HOME/imitator_genome/imitator.1.3.6.fa"
genome=$(basename $ASSEMBLY)
READS=$"$HOME/imitator_genome/raw_PacBio_data/R_imitator_PacBio.fa"


module load linuxbrew/colsa
conda activate purge_haplotigs

## purge haplotgis reference info: https://bitbucket.org/mroachawri/purge_haplotigs/src/master/

echo Running minimap on $READS and aligning to $ASSEMBLY

mkdir purge_haplotigs
cd purge_haplotigs

cp $ASSEMBLY .

minimap2 -t 40 -ax map-pb $genome $READS --secondary=no \
    | samtools sort -m 1G -o pacbio.aligned.bam -T tmp.ali

# generate histogram
purge_haplotigs hist -b pacbio.aligned.bam -g $genome -t 40

###### Manually examine histo to set parameters

# next step
purge_haplotigs  cov  -i aligned.bam.genecov  -l <integer>  -m <integer>  -h <integer>  \
            [-o coverage_stats.csv -j 80  -s 80 ]

REQUIRED:
-i / -in        The bedtools genomecov output that was produced from 'purge_haplotigs readhist'
-l / -low       The read depth low cutoff (use the histogram to eyeball these cutoffs)
-h / -high      The read depth high cutoff
-m / -mid       The low point between the haploid and diploid peaks

OPTIONAL:
-o / -out       Choose an output file name (CSV format, DEFAULT = coverage_stats.csv)
-j / -junk      Auto-assign contig as "j" (junk) if this percentage or greater of the contig is 
                low/high coverage (DEFAULT = 80, > 100 = don't junk anything)
-s / -suspect   Auto-assign contig as "s" (suspected haplotig) if this percentage or less of the
                contig is diploid level of coverage (DEFAULT = 80)

## final step..
purge_haplotigs  purge  -g genome.fasta  -c coverage_stats.csv

REQUIRED:
-g / -genome        Genome assembly in fasta format. Needs to be indexed with samtools faidx.
-c / -coverage      Contig by contig coverage stats csv file from the previous step.

OPTIONAL:
-t / -threads       Number of worker threads to use. DEFAULT = 4
-o / -outprefix     Prefix for the curated assembly. DEFAULT = "curated"
-r / -repeats       BED-format file of repeats to ignore during analysis.
-d / -dotplots      Generate dotplots for manual inspection.
-b / -bam           Samtools-indexed bam file of aligned and sorted reads/subreads to the
                    reference, required for generating dotplots.

ADVANCED:
-a / -align_cov     Percent cutoff for identifying a contig as a haplotig. DEFAULT = 70
-m / -max_match     Percent cutoff for identifying repetitive contigs. Ignored when 
                    using repeat annotations (-repeats). DEFAULT = 250
-I                  Minimap2 indexing, drop minimisers every N bases, DEFAULT = 4G
-v / -verbose       Print EVERYTHING.
-limit_io           Limit for I/O intensive jobs. DEFAULT = -threads
-wind_min           Min window size for BED coverage plots (for dotplots). DEFAULT = 5000
-wind_nmax          Max windows per contig for BED coverage plots (for dotplots). DEFAULT = 200	
