#!/bin/bash

#SBATCH --partition=macmanes
#SBATCH -J rails
#SBATCH --cpus-per-task=40
#SBATCH --output rails.${1}.log
#SBATCH --mem 700Gb
#SBATCH --exclude=node117,node118
set -x

module load linuxbrew/colsa

# set variables
ASSEMBLY=$1
ASSNAME=$(basename $ASSEMBLY)
READ_PARAMETERS=$2
ASSEMBLY_OUT=$3
READS="/mnt/lustre/macmaneslab/ams1236/imitator_genome/reads/combined_PacBio_Nanopore_reads.fa"
READNAME=$(basename $READS)
DIR=$(pwd)

mkdir rails_alldata_${READ_PARAMETERS}
cd rails_alldata_${READ_PARAMETERS}

cp ${DIR}/$ASSEMBLY .
ln -s $READS ${DIR}/rails_alldata_${READ_PARAMETERS}/$READNAME

runRAILSminimap.sh \
$ASSNAME \
$READNAME \
90 0.90 90 1 $READ_PARAMETERS \
~/linuxbrew/.linuxbrew/bin/samtools

# copy assembly into new name
cp *rails.scaffolds.fa $ASSEMBLY_OUT

# clean up big files
rm *bam
rm *formatted.fa
